apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack # Vital para que Prometheus lo detecte
spec:
  selector:
    matchExpressions:
      # Selecciona cualquier servicio que tenga la etiqueta "app"
      - key: app
        operator: Exists
  namespaceSelector:
    matchNames:
      - dev    # OJO: Tus servicios están en 'dev', no en 'default'
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s